class CreateAuthentications < ActiveRecord::Migration
  def change
    create_table :authentications do |t|
      t.string :uid 
      t.string :token
      t.string :provider
      t.references :user, index: true, foreign_key: true

      t.timestamps null: false
    end
  end
end

#uid: (a string generated by provider) uniquely identifies user 
#token: (a string generated by provider after successful authentication by provider of our app & approved authorization by the user)
# 	  : access token provides temporary, secure access to Facebook APIs